import { FurnitureItem } from '@/types/index';

export const FURNITURE_LIBRARY: FurnitureItem[] = [
  {
    id: 'plant-1',
    name: '🌿 Solar Succulent',
    type: 'plant',
    modelPath: '/models/solarpunk-village.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'panel-1',
    name: '⚡ Solar Panel Station',
    type: 'panel',
    modelPath: '/models/solarpunk-building.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'hydro-tower',
    name: '🌱 Hydroponic Tower',
    type: 'tower',
    modelPath: '/models/hydroponic-tower.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'chair-1',
    name: '🪑 Eco Chair',
    type: 'chair',
    modelPath: '/models/eco-chair.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'table-1',
    name: '🪵 Work Table',
    type: 'table',
    modelPath: '/models/work-table.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'lamp-1',
    name: '💡 Bio Lamp',
    type: 'lamp',
    modelPath: '/models/bio-lamp.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'sofa-1',
    name: '🛋️ Lounge Sofa',
    type: 'sofa',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'bookshelf-1',
    name: '📚 Bookshelf',
    type: 'bookshelf',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'rug-1',
    name: '🟫 Area Rug',
    type: 'rug',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'desk-1',
    name: '🖥️ Office Desk',
    type: 'desk',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'mirror-1',
    name: '🪞 Wall Mirror',
    type: 'mirror',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'vase-1',
    name: '🏺 Decorative Vase',
    type: 'vase',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'curtain-1',
    name: '🪟 Curtain Panel',
    type: 'curtain',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'bed-1',
    name: '🛏️ Eco Bed',
    type: 'bed',
    modelPath: '',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
];
