import { FurnitureItem } from '@/types/index';

export const FURNITURE_LIBRARY: FurnitureItem[] = [
  {
    id: 'plant-1',
    name: '🌿 Solar Succulent',
    type: 'plant',
    modelPath: '/models/solarpunk-village.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'panel-1',
    name: '⚡ Solar Panel Station',
    type: 'panel',
    modelPath: '/models/solarpunk-building.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'hydro-tower',
    name: '🌱 Hydroponic Tower',
    type: 'tower',
    modelPath: '/models/hydroponic-tower.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'chair-1',
    name: '🪑 Eco Chair',
    type: 'chair',
    modelPath: '/models/eco-chair.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'table-1',
    name: '🪵 Work Table',
    type: 'table',
    modelPath: '/models/work-table.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
  {
    id: 'lamp-1',
    name: '💡 Bio Lamp',
    type: 'lamp',
    modelPath: '/models/bio-lamp.glb',
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: 1,
  },
];
